- name: "Secure SSH: disable root login"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"

- name: "Secure SSH: disable password auth"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: Change ssh port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port "
    line: "Port {{ ssh_port }}"
    state: present
  notify: restart ssh

- name: Create default user
  user:
    name: "{{ default_user }}"
    comment: "Default user"
    shell: /bin/bash

- name: Add authorized_keys
  file:
    path: "/home/{{ default_user }}/.ssh/"
    state: directory

- name: Add authorized_keys
  copy:
    dest: "/home/{{ default_user }}/.ssh/authorized_keys"
    src: "files/home/user/.ssh/id_dsa.pub"

- name: Add sudo for default_user
  copy:
    dest: /etc/sudoers.d/010_defaut_user-nopasswd
    content: "{{ default_user }} ALL=(ALL) NOPASSWD: ALL"

- name: Remove 'pi' user
  user:
    name: pi
    state: absent
    force: yes

- name: Remove 'pi' sudos
  file:
    path: /etc/sudoers.d/010_pi-nopasswd
    state: absent
