- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install etckeeper
  apt:
    name: etckeeper

- name: Upgrade system
  apt:
    upgrade: safe

- name: Set hostname
  hostname:
    name: "{{ host_name }}"

- name: Set hostname
  template:
    src: templates/etc/hosts
    dest: /etc/hosts

- name: Set up Postfix to relay mail
  debconf:
    name: postfix
    question: '{{ item.question }}'
    value: '{{ item.value }}'
    vtype: '{{ item.vtype }}'
  with_items:
    - { question: 'postfix/mailname', value: '{{ host_name }}.{{ host_domain }}', vtype: 'string' }
    - { question: 'postfix/root_address', value: '{{ admin_mail }}', vtype: 'string' }
    - { question: 'postfix/main_mailer_type', value: 'Satellite system', vtype: 'string' }
    - { question: 'postfix/relayhost', value: '{{ mail_relay }}', vtype: 'string' }
    - { question: 'postfix/protocols', value: 'ipv4', vtype: 'string' }
    - { question: 'postfix/destinations', value: '{{ host_name }}, {{host_name}}.{{host_domain}}, localhost, localhost.localdomain', vtype: 'string' }
  tags:
    - postfix
  register: postfix_conf

- name: Relay mail to admin
  copy:
    content: "{{ admin_mail }}"
    dest: /root/.forward
  tags:
    - postfix

- name: Install tools
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - screen
    - tree
    - fail2ban
    - logwatch
    - postfix
    - vim
    - bsd-mailx

- name: Set vim as default editor
  alternatives:
    name: editor
    path: /usr/bin/vim
