- name: Disable screen blanking
  lineinfile:
    dest: /etc/kbd/config
    regexp: '^BLANK_TIME='
    line: 'BLANK_TIME=0'

- name: Disable auto start on TV
  lineinfile:
    dest: /boot/config.txt
    regexp: '^hdmi_ignore_cec_init='
    line: 'hdmi_ignore_cec_init=1'

- name: Install requirements
  apt:
    name: "{{ item }}"
  with_items:
    - python-pygame

- name: Create data directories
  file:
    path: "{{ item }}"
    owner: family_pi
    state: directory
  with_items:
    - "/srv/family_pi"
    - "/srv/family_pi/videos"
    - "/srv/family_pi/pictures"
    - "/srv/family_pi/movies"

- name: "Set sudo to light on/off"
  lineinfile:
    create: yes
    dest: "/etc/sudoers.d/090_family_py"
    line: "family_pi ALL=(ALL) NOPASSWD: {{ app_path }}/bin/light-on, NOPASSWD: {{ app_path }}/light-off"
    validate: 'visudo -cf %s'

- name: Install app
  git:
    repo: https://github.com/seb4stien/family_box.git
    dest: "{{ app_path }}"
