- name: Disable screen blanking
  lineinfile:
    dest: /etc/kbd/config
    regexp: '^BLANK_TIME='
    line: 'BLANK_TIME=0'

- name: Disable auto start on TV
  lineinfile:
    dest: /boot/config.txt
    regexp: '^hdmi_ignore_cec_init='
    line: 'hdmi_ignore_cec_init=1'

- name: Install requirements
  apt:
    name: "{{ item }}"
  with_items:
    - python-pygame
    - virtualenv
    - omxplayer
    - python-pip
    - python-dbus
    - cec-utils
    - apache2
    - libapache2-mod-php5

- name: Create data directories
  file:
    path: "{{ item }}"
    owner: family_pi
    state: directory
  with_items:
    - "/mnt/media"
    - "/mnt/media/videos"
    - "/mnt/media/pictures"
    - "/mnt/media/movies"

- name: "Set sudo to light on/off"
  lineinfile:
    create: yes
    dest: "/etc/sudoers.d/090_family_py"
    line: "family_pi ALL=(ALL) NOPASSWD: {{ app_path }}/bin/light-on, NOPASSWD: {{ app_path }}/light-off"
    validate: 'visudo -cf %s'

- name: Install app
  git:
    repo: https://github.com/seb4stien/family_box.git
    dest: "{{ app_path }}"

- name: Install requirement
  pip:
    name: omxplayer-wrapper
    virtualenv: "{{ app_path }}_venv"
    virtualenv_site_packages: yes

- name: Set gui on boot
  blockinfile:
    dest: /etc/rc.local
    block: |
      . /opt/family_pi_venv/bin/activate
      python /opt/family_pi/family_box/gui.py
    insertbefore: "exit 0"
  tags:
    - tmp
