- name: Disable screen blanking
  lineinfile:
    dest: /etc/kbd/config
    regexp: '^BLANK_TIME='
    line: 'BLANK_TIME=0'

- name: Disable auto start on TV
  lineinfile:
    dest: /boot/config.txt
    regexp: '^hdmi_ignore_cec_init='
    line: 'hdmi_ignore_cec_init=1'

- name: Install requirements
  apt:
    name: "{{ item }}"
  with_items:
    - python-pygame
