- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install etckeeper
  apt:
    name: etckeeper

- name: Set hostname
  hostname:
    name: "{{ host_name }}"  

- name: Set hostname
  template:
    src: templates/etc/hosts
    dest: /etc/hosts

- name: Set up Postfix to relay mail
  debconf:
    name: postfix
    question: '{{ item.question }}'
    value: '{{ item.value }}'
    vtype: '{{ item.vtype }}'
  with_items:
    - { question: 'postfix/mailname', value: '{{ host_name }}.{{ host_domain }}', vtype: 'string' }
    - { question: 'postfix/main_mailer_type', value: 'Internet with smarthost', vtype: 'string' }
    - { question: 'postfix/relayhost', value: '{{ mail_relay }}', vtype: 'string' }
    - { question: 'postifx/destinations', value: '{{ host_name }}, {{host_name}}.{{host_domain}}, localhost, localhost.localdomain', vtype: 'string' }

- name: Install tools
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - screen
    - tree
    - fail2ban
    - logwatch
    - postfix
    - vim
    - bsd-mailx

- name: Set vim as default editor
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: "Secure SSH: disable root login"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"

- name: "Secure SSH: disable password auth"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: Create default user
  user:
    name: "{{ default_user }}"
    comment: "Default user"

- name: Add authorized_keys
  file:
    path: "/home/{{ default_user }}/.ssh/"
    state: directory

- name: Add authorized_keys
  copy:
    dest: "/home/{{ default_user }}/.ssh/authorized_keys"
    src: "files/home/user/.ssh/id_dsa.pub"

- name: Add sudo for default_user
  copy:
    dest: /etc/sudoers.d/010_defaut_user-nopasswd
    content: "{{ default_user }} ALL=(ALL) NOPASSWD: ALL"

- name: Change ssh port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port "
    line: "Port {{ ssh_port }}"
    state: present
  notify: restart ssh

- name: Remove 'pi' user
  user:
    name: pi
    state: absent
    force: yes

- name: Remove 'pi' sudos
  file:
    path: /etc/sudoers.d/010_pi-nopasswd
    state: absent

- name: Disable IPv6
  copy:
    src: files/boot/cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
