- hosts: localhost

  handlers:
  - include: "handlers/main.yml"

  tasks:
  - include: "tasks/system.yml"
    tags: system
  - include: "tasks/network.yml"
    tags: network
  - include: "tasks/cron.yml"
    tags: cron
  - include: "tasks/family_box.yml"
    tags: family_box
