- hosts: localhost

  vars:
  - default_user: family_pi
  - ssh_port: 29226
  - host_name: pi_grandma
  - host_domain: familypi.net
  - mail_relay: smtp.free.fr

  handlers:
  - include: "handlers/main.yml"

  tasks:
  - include: "tasks/system.yml"
  - include: "tasks/family_box.yml"
  - include: "tasks/network.yml"
