- hosts: localhost
  become: true

  handlers:
  - include: "handlers/main.yml"

  tasks:
  - include: "tasks/configure_network.yml"
    tags: network
  - include: "tasks/configure_access.yml"
    tags: access 
  - include: "tasks/configure_system.yml"
    tags: system
  - include: "tasks/family_box.yml"
    tags: family_box
    when: family_box == True
