- hosts: localhost

  handlers:
  - include: "handlers/main.yml"

  tasks:
  - include: "tasks/configure_network.yml"
    tags: network
  - include: "tasks/configure_access.yml"
    tags: access 
  - include: "tasks/configure_system.yml"
    tags: system
  - include: "tasks/box_base.yml"
    tags: family_box
  - include: "tasks/box_webapp.yml"
    tags: family_box
